services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: erp_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: Dw00922948
      MYSQL_USER: erp_user
    volumes:
      - erp_db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/.env:/var/www/.env
      - storage_data:/var/www/storage/app/public
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Já deixe a 443 pronta para o HTTPS
    volumes:
      - ./backend/public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot # ADICIONE ESTA LINHA
      - ./certbot/conf:/etc/letsencrypt # ADICIONE ESTA LINHA TAMBÉM
    depends_on:
      - backend

volumes:
  erp_db_data:
  storage_data: