services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: realize_pilates_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: secretpassword
      MYSQL_USER: erp_user
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - storage_data:/var/www/storage/app/public
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend/public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  db_data:
  storage_data: