server {
    listen 80;
    server_name inovabi.com api.inovabi.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 404; # Por enquanto, só queremos validar o SSL
    }
}