server {
    listen 80;
    server_name inovabi.com api.inovabi.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot/; # Verifique se a barra final está aqui
    }

    location / {
        return 404; 
    }
}